### ISSUE TITLE
java/17_skiplist/Skiplist2对insert方法中对前驱结点遍历层数的优化其实是过度设计没有必要

### ISSUE THREAD

**Issue by evilkevinhe** [wangzheng0822/algo#483]
老师原有insert方法中统计新增节点前驱指针数组即update[]时，是从新增节点的随机层数的最大层level-1开始遍历
而你觉得不妥，认为应该从已有数据最大层levelCount-1开始遍历，你的理由是如果数据量为1亿，随机level=1 ，那么插入时间复杂度为O（n），我觉得并不然，因为即使从levelCount-1开始病例，还是会由上到下遍历到最底层，找最底层的前驱节点
你这种从levelCount-1开始的遍历方法如你的优化方法所写还增加了判断条件if (level > i)，增加逻辑的复杂度。除此之外如果新增节点的随机层数level小于levelCount，还增加了多余的计算和赋值，因为[level-1,levelCount-1]的前驱节点根本不需要寻找
btw你insert2的方法不需要借助update[]存储前驱结点，直接在寻找前驱节点过程中完成了插入，而且一个循环完成了两个循环的工作这样节省了时间和空间复杂度，应该是没什么问题的
@lidb

**Comment by lidb** [comment]
你好，
&nbsp; &nbsp; &nbsp;根据你发的内容，我感觉你没有理解清楚！如果数据量为1亿，随机level=1 ，因为是从head开始遍历，那么插入时间复杂度为O（n）这没有问题。如果不从levelCount-1开始找，就没有体现索引的价值了。
&nbsp; &nbsp; &nbsp;如果还是没有理解到，欢迎添加我的微信讨论，微信：lovelife1q&nbsp; &nbsp;&nbsp;












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangzheng0822/algo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 下午4:50
收件人:&nbsp;"wangzheng0822/algo"<algo@noreply.github.com&gt;;
抄送:&nbsp;"天仙才子"<ldbdream@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;[wangzheng0822/algo] java/17_skiplist/Skiplist2对insert方法中对前驱结点遍历层数的优化其实是过度设计没有必要 (#483)





 
老师原有insert方法中统计新增节点前驱指针数组即update[]时，是从新增节点的随机层数的最大层level-1开始遍历
 而你觉得不妥，认为应该从已有数据最大层levelCount-1开始遍历，你的理由是如果数据量为1亿，随机level=1 ，那么插入时间复杂度为O（n），我觉得并不然，因为即使从levelCount-1开始病例，还是会由上到下遍历到最底层，找最底层的前驱节点
 你这种从levelCount-1开始的遍历方法如你的优化方法所写还增加了判断条件if (level &gt; i)，增加逻辑的复杂度。除此之外如果新增节点的随机层数level小于levelCount，还增加了多余的计算和赋值，因为[level-1,levelCount-1]的前驱节点根本不需要寻找
 btw你insert2的方法不需要借助update[]存储前驱结点，直接在寻找前驱节点过程中完成了插入，这点节省了空间复杂度，应该是没什么问题的
 @lidb

**Comment by evilkevinhe** [comment]
@lidb 明白了你是对的，我想通了，当新增结点的随机层数远小于现有跳表层数时，也就是你说的这种场景下，是从比较低层的索引开始查找的，遍历次数就太多了，但如果随机层数跟现有层数差不多时就还好
