### ISSUE TITLE
python 中的数组部分，delete方法有问题

### ISSUE THREAD

**Issue by AndyClouder** [wangzheng0822/algo#49]
def delete(self, index: int) -> bool:
        if index >= self._count or index <= -self._count: return False
        self._data[index:-1] = self._data[index+1:]
        self._count -= 1
return True

这里delete虽然有移位，但是最后一个元素没有删除, 那就会引起删除之后insert失败的效果

i.e.
a = MyArray(6)
for i in range(6):
    a.insert_to_tail(i)
print(a)
out: 0 1 2 3 4 5

a.delete(2)
print(a)
out: 0 1 3 4 5    ---> "其实索引为5的值还是5，只是没有显示"

a.insert_to_tail(7)
print(a)
out: 0 1 3 4 5 5  ---> "这里就出现了问题了"

**Comment by jerryderry** [comment]
你说的没错，可以把insert_to_tail改一下

**Comment by wangzheng0822** [comment]
麻烦提个pull request 改下吧

**Comment by jerryderry** [comment]
这个已经改完merge进去了

**Comment by jerryderry** [comment]
请教一下，像这种针对特定的issue的修复，我要怎么提交pull request？

**Comment by wenshuo001** [comment]
java也是一样的

**Comment by theonsoong** [comment]
`self._data[index:] = self._data[index+1:]`这样就可以删除元素了。

**Comment by jerryderry** [comment]
> `self._data[index:] = self._data[index+1:]`这样就可以删除元素了。

是个好办法。但是会不会在某些时候list本身allocate的array的大小被缩小了？

**Comment by Liam0205** [comment]
This was fixed by 01ae89d478c51703914e1a9b161c1b8c4471c476, as a notification to @wangzheng0822 .

**Comment by AndyClouder** [comment]
Good!
