### ISSUE TITLE
Java 中的数组部分，插入元素的时候好像存在问题

### ISSUE THREAD

**Issue by bigrotor187** [wangzheng0822/algo#60]
if (index<0 || index>=count) return false;

刚开始插入元素的时候， index >= count 就会出问题，因为 count 初始化为 0，所以即使从头开始插入（即 index = 0），也插入不成功。换句话说根本插入不了元素，我觉得应该改成将 index >= count 改成 index > count：

if (index<0 || index > count) return false; 

不知道理解对不对。

**Comment by lmxiels** [comment]
Sorts.java中的insertionSort（插入排序），输入值[9, 2, 3, 4]排序以后值是[2, 3, 9, 4]，有问题 麻烦作者看一下

**Comment by kimmazhenxin** [comment]
是的，我一开始也是这样子，因为初始化时候元素为0，后来去掉了“=”就ok了
